<?php

//AWS BASE URL
const AWS_BASE_URL = '';

// AWS LIVE URL
const LIVE_USER_PICTURE_PATH = AWS_BASE_URL;
const LIVE_COMPANY_PICTURE_PATH = AWS_BASE_URL;
const LIVE_USER_RESUME_PATH = AWS_BASE_URL;
const AWSJS = AWS_BASE_URL;
const AWS_CSS = AWS_BASE_URL;
const AWS_HOME_CSS = AWS_BASE_URL;
const AWS_HOME_JS = AWS_BASE_URL;

// AWS TESTING URL
const TESTING_USER_PICTURE_PATH = AWS_BASE_URL;
const TESTING_COMPANY_PICTURE_PATH = AWS_BASE_URL;
const TESTING_USER_RESUME_PATH = AWS_BASE_URL;
const TESTING_AWS_JS = AWS_BASE_URL;
const TESTING_AWS_CSS = AWS_BASE_URL;
const TESTING_AWS_HOME_CSS = AWS_BASE_URL;
const TESTING_AWS_HOME_JS = AWS_BASE_URL;

// Whatsapp allowed
const IS_WHATSAPP_ALLOWED = 0;

//developer email
const DEVELOPER_EMAIL = [''];

// Others
const VERSION = 1.35;
const MIN_THRESHOLD_FOR_WITHDRAW = 30;
const G_RECAPTCHA_SITE_KEY = '';
const G_RECAPTCHA_PRIVATE_KEY = '';

return [
    'options' => [
        'send_email' => '13',
    ]
];